//! One-click decompilation project export.

use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecompFunction {
    pub address: u64, pub name: String, pub size: usize,
    pub is_named: bool, pub source: FunctionSource,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FunctionSource { SymbolTable, Heuristic, SdkMatch }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecompSection {
    pub name: String, pub address: u64, pub size: usize,
    pub is_code: bool, pub file_offset: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecompExportResult {
    pub project_dir: String, pub files_written: Vec<String>,
    pub function_count: usize, pub named_count: usize,
    pub sdk_named_count: usize, pub section_count: usize,
    pub platform: String, pub binary_name: String, pub entry_point: u64,
}

pub fn generate_decomp_project(
    binary_name: &str, platform: &str, sections: &[DecompSection],
    functions: &[DecompFunction], entry_point: u64, output_dir: &str,
    is_little_endian: bool,
) -> DecompExportResult {
    let dir = output_dir.trim_end_matches('/');
    let mut files = Vec::new();
    let write = |name: &str, content: &str, files: &mut Vec<String>| {
        let p = format!("{}/{}", dir, name);
        let _ = std::fs::write(&p, content); files.push(p);
    };
    write("functions.csv", &generate_functions_csv(functions), &mut files);
    write("symbol_addrs.txt", &generate_symbol_addrs(functions), &mut files);
    write("undefined_syms.txt", &generate_undefined_syms(functions), &mut files);
    write("splat.yaml", &generate_splat_yaml(binary_name, platform, sections, functions, entry_point, is_little_endian), &mut files);
    write("functions.json", &generate_functions_json(binary_name, platform, sections, functions, entry_point), &mut files);
    write("symbols.idc", &generate_symbols_idc(functions), &mut files);
    write("config.toml", &generate_config_toml(binary_name, platform, sections, functions, entry_point, dir), &mut files);
    let mk = generate_makefile(binary_name, platform);
    let bd = format!("{}/build", dir); let _ = std::fs::create_dir_all(&bd);
    let mkp = format!("{}/Makefile", bd); let _ = std::fs::write(&mkp, &mk); files.push(mkp);
    write("README.md", &generate_readme(binary_name, platform, functions, sections), &mut files);
    let named = functions.iter().filter(|f| f.is_named).count();
    let sdk = functions.iter().filter(|f| f.source == FunctionSource::SdkMatch).count();
    DecompExportResult { project_dir: dir.to_string(), files_written: files,
        function_count: functions.len(), named_count: named, sdk_named_count: sdk,
        section_count: sections.len(), platform: platform.to_string(),
        binary_name: binary_name.to_string(), entry_point }
}

pub fn generate_functions_csv(functions: &[DecompFunction]) -> String {
    let mut c = String::from("Name,Start,End,Size\n");
    for f in functions { c.push_str(&format!("{},0x{:08X},0x{:08X},{}\n", f.name, f.address, f.address + f.size as u64, f.size)); }
    c
}

pub fn generate_symbol_addrs(functions: &[DecompFunction]) -> String {
    let mut s = String::from("# Auto-generated symbol address mappings\n# Format: symbol_name = 0xADDRESS\n\n");
    for f in functions { if f.is_named { s.push_str(&format!("{} = 0x{:08X}\n", f.name, f.address)); } }
    s
}

pub fn generate_undefined_syms(functions: &[DecompFunction]) -> String {
    let mut s = String::from("# Functions without a known name\n\n");
    for f in functions { if !f.is_named { s.push_str(&format!("0x{:08X}\n", f.address)); } }
    s
}

pub fn generate_splat_yaml(binary_name: &str, platform: &str, sections: &[DecompSection], functions: &[DecompFunction], _entry: u64, le: bool) -> String {
    let mut y = format!("# splat.yaml - auto-generated by Aura Decomp Tool\n# Platform: {}\n# Binary: {}\n\noptions:\n  basename: {}\n  target_path: \"{}\"\n  base_path: \".\"\n  platform: \"{}\"\n  compiler: \"GCC\"\n  endianness: \"{}\"\n\nsegments:\n",
        platform, binary_name, binary_name.split('.').next().unwrap_or(binary_name), binary_name, platform.to_lowercase(), if le {"little"} else {"big"});
    for sec in sections {
        y.push_str(&format!("  - name: {}\n    type: {}\n    start: 0x{:08X}\n    vram: 0x{:08X}\n    size: 0x{:X}\n",
            sec.name.trim_start_matches('.'), if sec.is_code {"code"} else {"data"}, sec.address, sec.address, sec.size));
        if sec.is_code {
            y.push_str("    subsegments:\n");
            for f in functions { if f.address >= sec.address && f.address < sec.address + sec.size as u64 {
                y.push_str(&format!("      - [0x{:08X}, asm, {}]\n", f.address, f.name)); }}
        }
        y.push('\n');
    }
    y.push_str("  - name: shiftd\n    type: bin\n    starts:\n      - 0x0\n");
    y
}

pub fn generate_config_toml(binary_name: &str, platform: &str, sections: &[DecompSection], functions: &[DecompFunction], entry: u64, out: &str) -> String {
    let named = functions.iter().filter(|f| f.is_named).count();
    let sdk = functions.iter().filter(|f| f.source == FunctionSource::SdkMatch).count();
    let sym = functions.iter().filter(|f| f.source == FunctionSource::SymbolTable).count();
    let heu = functions.len() - sym - sdk;
    format!("# Auto-generated by Aura Decomp Tool\n# Platform: {}\n# Binary: {}\n# Entry: 0x{:08X}\n\n# {} SDK-named, {} from symbols, {} heuristic\n\n[general]\ninput = \"{}\"\noutput = \"{}\"\nsingle_file_output = false\npatch_syscalls = false\nstubs = []\nskip = []\n\n[binary_info]\nentry_point = \"0x{:08X}\"\nsections = {}\nfunctions = {}\nnamed = {}\nsdk_named = {}\n",
        platform, binary_name, entry, sdk, sym, heu, binary_name, out, entry, sections.len(), functions.len(), named, sdk)
}

pub fn generate_makefile(binary_name: &str, platform: &str) -> String {
    let tc = match platform {
        "PS1"|"PS2" => "mips-elf", "PS3" => "ppu-lv2",
        "PS4"|"PS5" => "x86_64-pc-freebsd12", "Xbox" => "i686-w64-mingw32",
        "Xbox 360" => "ppc-xenon", "Wii U"|"GameCube"|"Wii" => "powerpc-eabi",
        _ => "gcc",
    };
    format!("# Makefile - auto-generated by Aura Decomp Tool\n# Platform: {}\n# Toolchain: {}\n\nCC = {tc}-gcc\nAS = {tc}-as\nLD = {tc}-ld\nCFLAGS = -O2 -G 0 -Wall -c\nLDFLAGS = -T linker.ld -Map build.map\nSRC = ../src\nBIN = {bin}\n\nall: $(BIN)\n$(BIN): $(SRC)/*.c $(SRC)/*.s\n\t$(LD) $(LDFLAGS) -o $@ $^\nclean:\n\trm -f *.o $(BIN) build.map\n.PHONY: all clean\n", platform, tc, tc=tc, bin=binary_name)
}

pub fn generate_readme(binary_name: &str, platform: &str, functions: &[DecompFunction], sections: &[DecompSection]) -> String {
    let named = functions.iter().filter(|f| f.is_named).count();
    let mut r = format!("# Decompilation Project: {}\n\n**Platform:** {}\n**Functions:** {} total, {} named, {} unnamed\n\n## Files\n\n- `config.toml` - recompiler configuration\n- `functions.csv` - function table\n- `symbol_addrs.txt` - address to name mappings\n- `undefined_syms.txt` - unnamed function addresses\n- `splat.yaml` - segment splitter config\n- `functions.json` - machine-readable function/section export\n- `symbols.idc` - IDA symbol import script\n- `build/Makefile` - build scaffold\n\n## Getting Started\n\n1. Review `symbol_addrs.txt` for known function names\n2. Name functions in `undefined_syms.txt`\n3. Use `splat.yaml` with splat to split the binary\n4. Start writing C source files in `src/`\n5. Build with `make -C build`\n\n",
        binary_name, platform, functions.len(), named, functions.len() - named);
    if named > 0 {
        r.push_str("## Named Functions\n\n");
        for f in functions.iter().filter(|f| f.is_named).take(50) { r.push_str(&format!("- `0x{:08X}` - {}\n", f.address, f.name)); }
        if named > 50 { r.push_str(&format!("\n... and {} more\n", named - 50)); }
        r.push('\n');
    }
    r.push_str("## Sections\n\n| Name | Address | Size | Type |\n|------|---------|------|------|\n");
    for s in sections { r.push_str(&format!("| {} | 0x{:08X} | 0x{:X} | {} |\n", s.name, s.address, s.size, if s.is_code {"code"} else {"data"})); }
    r
}

/// Emit a machine-readable `functions.json` documenting the whole deployment
/// (platform, binary, entry point, sections and functions). This is the format
/// external tooling (build systems, recompilers, dashboards) should consume.
pub fn generate_functions_json(
    binary_name: &str, platform: &str, sections: &[DecompSection],
    functions: &[DecompFunction], entry_point: u64,
) -> String {
    let named = functions.iter().filter(|f| f.is_named).count();
    let secs: Vec<serde_json::Value> = sections
        .iter()
        .map(|s| json!({
            "name": s.name,
            "address": format!("0x{:08X}", s.address),
            "address_raw": s.address,
            "size": s.size,
            "is_code": s.is_code,
            "file_offset": format!("0x{:X}", s.file_offset),
        }))
        .collect();
    let funcs: Vec<serde_json::Value> = functions
        .iter()
        .map(|f| json!({
            "name": f.name,
            "address": format!("0x{:08X}", f.address),
            "address_raw": f.address,
            "size": f.size,
            "is_named": f.is_named,
            "source": format!("{:?}", f.source),
        }))
        .collect();
    json!({
        "tool": "Aura Decomp Tool",
        "platform": platform,
        "binary_name": binary_name,
        "entry_point": format!("0x{:08X}", entry_point),
        "section_count": sections.len(),
        "function_count": functions.len(),
        "named_count": named,
        "sections": secs,
        "functions": funcs,
    })
    .to_string()
}

/// Emit an IDA Pro `.idc` script that names every known function at its
/// address. Load via File → IDC file… in IDA.
pub fn generate_symbols_idc(functions: &[DecompFunction]) -> String {
    let mut s = String::from("// Auto-generated by Aura Decomp Tool — IDA symbol map\n");
    s.push_str("// Load with File → IDC file…, or paste into the IDA IDC console.\n");
    s.push_str("static main() {\n");
    for f in functions.iter().filter(|f| f.is_named) {
        // Sanitize the name for the IDC string literal and MakeNameEx.
        let n = f.name.replace('\\', "_").replace('"', "_");
        s.push_str(&format!(
            "    MakeNameEx(0x{:08X}, \"{}\", SN_NOWARN|SN_FORCE|SN_NODEFAULT);\n",
            f.address, n
        ));
    }
    s.push_str("}\n");
    s
}
